Required Variables (#11)

diff --git a/create-release/action.yaml b/create-release/action.yaml
--- a/create-release/action.yaml
+++ b/create-release/action.yaml
@@ -21,6 +21,25 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Validate required inputs
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.version }}" ]; then
+          echo "Missing required input: version"
+          exit 1
+        fi
+        if [ -z "${{ inputs.github_token }}" ]; then
+          echo "Missing required input: github_token"
+          exit 1
+        fi
+        if [ -z "${{ inputs.project_name }}" ]; then
+          echo "Missing required input: project_name"
+          exit 1
+        fi
+        if [ -z "${{ inputs.target_commitish }}" ]; then
+          echo "Missing required input: target_commitish"
+          exit 1
+        fi
     - name: Create Release
       id: create_release
       uses: softprops/action-gh-release@v2
diff --git a/health-check/action.yaml b/health-check/action.yaml
--- a/health-check/action.yaml
+++ b/health-check/action.yaml
@@ -18,6 +18,12 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Validate required inputs
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.url }}" ]; then
+          echo "Missing required input: url"
+          exit 1
     - run: |
         echo "Waiting 10 seconds before health check..."
         sleep ${{ inputs.sleep_before_check }}
