changes

diff --git a/build-publish-docker/action.yaml b/build-publish-docker/action.yaml
--- a/build-publish-docker/action.yaml
+++ b/build-publish-docker/action.yaml
@@ -30,6 +30,40 @@ outputs:
 runs:
   using: "composite"
   steps:
+  
+    - name: Validate required inputs
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.registry }}" ]; then
+          echo "Missing required input: registry"
+          exit 1
+        fi
+
+        if [ -z "${{ inputs.image_name }}" ]; then
+          echo "Missing required input: image_name"
+          exit 1
+        fi
+
+        if [ -z "${{ inputs.registry_username }}" ]; then
+          echo "Missing required input: registry_username"
+          exit 1
+        fi
+
+        if [ -z "${{ inputs.registry_password }}" ]; then
+          echo "Missing required input: registry_password"
+          exit 1
+        fi
+
+        if [ -z "${{ inputs.version }}" ]; then
+          echo "Missing required input: version"
+          exit 1
+        fi
+
+        if [ -z "${{ inputs.dockerfile_context }}" ]; then
+          echo "Missing required input: dockerfile_context"
+          exit 1
+        fi
+
     - uses: docker/setup-buildx-action@v3
 
     - uses: docker/login-action@v3
